#lang racket
(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (display guess)
     (newline)
    (if (close-enough? guess (f guess))
          (f guess) (try (f guess)))
    )
  (try first-guess))
(define (average x y) (/ (+ x y) 2))
(fixed-point (lambda (y) (average y (lambda(x)(/ (log 1000) (log x))))) 2.0)