#lang racket
(define (sqrt-iter guess x)
  (display guess)
  (display "\n")
  (if (good-enough? guess x)
      guess
      (sqrt-iter (improve guess x)
                 x)))
(define (improve guess x)
  (/ (+ (/ x (* guess guess)) (* 2 guess)) 3))
(define (average x y)
  (/ (+ x y) 2))
(define (good-enough? guess x)
  (< (abs (- (* guess guess guess) x)) 0.001))
(define (sqrt x) (sqrt-iter 1.0 x))
(sqrt 8)
