#lang racket
(define balance 5)
(define (withdraw amount)
  (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
(define (deposit amount)
  (begin (set! balance (+ balance amount))
             balance))
(define (make-accumulator amount)
  deposit)
(define A (make-accumulator 5))
(A 10)
(A 10)