(define (make-queue)
    (let ((front-ptr '())
          (rear-ptr '())
          (backward-front-ptr '())
          (backward-rear-ptr '()))
        (define (insert-queue! item)
            (if (null? front-ptr)
                    (begin
                        (set! front-ptr (list item))
                        (set! rear-ptr front-ptr)
                        (set! backward-front-ptr rear-ptr)
                        (set! backward-rear-ptr front-ptr)
                        front-ptr)
                    (begin
                        (set-cdr! rear-ptr (list item))
                        (set! rear-ptr (cdr rear-ptr))
                        (set! backward-front-ptr rear-ptr)
                        front-ptr)))
      (define (insert-queue-front! item)
            (if (null? front-ptr)
                    (begin
                        (set! front-ptr (list item))
                        (set! rear-ptr front-ptr)
                        (set! backward-front-ptr rear-ptr)
                        (set! backward-rear-ptr front-ptr)
                        front-ptr)
                    (begin
                      (let
                        ((tempfront (cons item front-ptr)))
                        (set! front-ptr tempfront)
                        (set! backward-rear-ptr front-ptr)
                        front-ptr))))
        (define (delete-queue!)
            (set! front-ptr (cdr front-ptr))
            (set! backward-rear-ptr front-ptr)
                    front-ptr)
        (define (dispatch m)
            (cond ((eq? m 'insert-queue!)
                    insert-queue!)
                  ((eq? m 'insert-queue-front!)
                    insert-queue-front!)
                  ((eq? m 'delete-queue!)
                    (delete-queue!))))
        dispatch))

(define q (make-queue))
((q 'insert-queue!) 'a)
((q 'insert-queue!) 'b)
((q 'insert-queue!) 'c)
((q 'insert-queue!) 'd)
((q 'insert-queue-front!) 'e)
(q 'delete-queue!)