#lang racket
(define balance 5)
(define (withdraw amount)
  (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
(define (deposit amount)
  (begin (set! balance (+ balance amount))
             balance))

(define (acc amount password)
  (if (eq? password '123456)
      (deposit amount)
      (display 'Incorrect password)
      )
  )
(acc 10 '123456)
(acc 10 'wwww)