#lang racket
(define balance 5)
(define false-input-count 0)
(define (withdraw amount)
  (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
(define (deposit amount)
  (begin (set! balance (+ balance amount))
             balance))

(define (acc amount password)
  (if (eq? password '123456)
      (begin
        (set! false-input-count 0)
        (deposit amount))
      (if (< false-input-count 3)
          (begin
            (set! false-input-count (+ false-input-count 1))
            (display 'Incorrect-password))
          (display 'Call-the-cops)
      )
   )
)
(acc 10 '123456)
(acc 10 'wwww)
(acc 10 'wwww)
(acc 10 'wwww)
(acc 10 'wwww)